import { Router } from 'express';
import authRoutes from './auth.routes.js';
import { categoryRouter, menuRouter } from './menu.routes.js';
import menuDocRoutes from './menuDocument.routes.js';
import galleryRoutes from './gallery.routes.js';
import reviewRoutes from './review.routes.js';
import enquiryRoutes from './enquiry.routes.js';
import visitRoutes from './visit.routes.js';
import { businessRouter, hoursRouter, settingsRouter, siteRouter } from './site.routes.js';
import { aboutRouter, heroRouter, homeRouter, sectionRouter } from './content.routes.js';
import { overview } from '../controllers/dashboard.controller.js';
import { requireAdmin } from '../middleware/auth.middleware.js';

const api = Router();
api.get('/health', (_req, res) => res.json({ success: true, status: 'ok' }));
api.use('/auth', authRoutes);
api.use('/site', siteRouter);
api.use('/site-settings', settingsRouter);
api.use('/business', businessRouter);
api.use('/opening-hours', hoursRouter);
api.use('/heroes', heroRouter);
api.use('/about', aboutRouter);
api.use('/home', homeRouter);
api.use('/home-sections', sectionRouter);
api.use('/menu', menuRouter);
api.use('/menu-categories', categoryRouter);
api.use('/menu-documents', menuDocRoutes);
api.use('/gallery', galleryRoutes);
api.use('/reviews', reviewRoutes);
api.use('/enquiries', enquiryRoutes);
api.use('/visits', visitRoutes);
api.get('/dashboard', requireAdmin, overview);
export default api;
